# -*- uft-8 -*-

class BindType(object):

    DATA_BIND = 'data_bind'
    EVENT_BIND = 'event_bind'

class EVENT_TYPE(object):

    TOUCH_EVENT_BEGAN = 0
    TOUCH_EVENT_MOVED = 1
    TOUCH_EVENT_ENDED = 2
    TOUCH_EVENT_CANCELED = 3

    TEXTFIELD_EVENTTYPE_ATTACH_WITH_IME = 0
    TEXTFIELD_EVENTTYPE_DETACH_WITH_IME = 1
    TEXTFIELD_EVENTTYPE_INSERT_TEXT = 2 
    TEXTFIELD_EVENTTYPE_DELETE_BACKWARD = 3 
    TEXTFIELD_EVENT_ATTACH_WITH_IME = 0
    TEXTFIELD_EVENT_DETACH_WITH_IME = 1
    TEXTFIELD_EVENT_INSERT_TEXT = 2
    TEXTFIELD_EVENT_DELETE_BACKWARD = 3

     



